/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import ordersDashboard from "../../src/plugins/orders-dashboard/strapi-admin";
import tiffinOrdersDashboard from "../../src/plugins/tiffin-orders-dashboard/strapi-admin";
import enquiryDashboard from "../../src/plugins/enquiry-dashboard/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "orders-dashboard": ordersDashboard,
    "tiffin-orders-dashboard": tiffinOrdersDashboard,
    "enquiry-dashboard": enquiryDashboard,
  },
});
